name: Update TOCs

on:
  workflow_dispatch:
  push:
    paths:
      - 'xslts/toc/correspondences/**'
      - 'indices/listcorrespondence.xml'
      - 'editions/**'

jobs:
  regenerate-tocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java (for Saxon)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Saxon HE
        run: |
          curl -L -o saxon.jar https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/11.6/Saxon-HE-11.6.jar

      - name: Run XSLT to regenerate TOCs via named template
        run: |
          mkdir -p tocs
          java -cp saxon.jar net.sf.saxon.Transform \
            -xsl:xslts/toc/correspondences/01_create-correspondence-tocs.xsl \
            -it:main

      - name: Commit updated TOCs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tocs/
          git diff --quiet && echo "No changes" || git commit -m "Update TOCs via workflow"
          git push
